clear all;
cd 'C:\Users\harsh\Downloads\eeglab13_4_4b'

%% // EEG DATA
eegData = csvread('C:\Users\harsh\Downloads\eeglab13_4_4b\Ferda1.csv');
eegData= eegData (:,2:15);
eegData = eegData';

%% // Importing subject data into eeglab
[ALLEEG EEG CURRENTSET ALLCOM] = eeglab;
EEG = pop_importdata('dataformat','array','nbchan',14,'data','eegData','srate',128,'pnts',0,'xmin',0);
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 0,'setname','','gui','off'); 

%% // Filtering Channels to remove line noise
EEG = pop_eegfiltnew(EEG, 4, 45, 212, 0, [], 0);
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 1,'gui','off'); 

eeglab redraw
EEG.event.latency = 0;

%% // Importing event file
EEG = eeg_checkset( EEG );
EEG = pop_importevent( EEG, 'append','no','event','C:\\Users\\harsh\\Downloads\\eeglab13_4_4b\\Final\\im.txt',...
    'fields',{'latency' 'type'},'skipline',1,'timeunit',1);
[ALLEEG EEG] = eeg_store(ALLEEG, EEG, CURRENTSET);
EEG = eeg_checkset( EEG );
pop_eegplot( EEG, 1, 1, 1);

%% // Eventlist
EEG  = pop_creabasiceventlist( EEG , 'BoundaryNumeric', { 1  2 }, 'BoundaryString',...
    { 'noChange ' 'control' }, 'Eventlist', 'C:\Users\harsh\Downloads\eeglab13_4_4b\Final\Af.txt' ); 
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 2,'gui','off'); 

%% // BDF
EEG  = pop_binlister( EEG , 'BDF', 'C:\Users\harsh\Downloads\eeglab13_4_4b\Final\bdf.txt', 'ExportEL',...
    'C:\Users\harsh\Downloads\eeglab13_4_4b\Final\Af.txt', 'IndexEL',  1,...% change file location for event list
    'SendEL2', 'All', 'UpdateEEG', 'on',... 
    'Voutput', 'EEG' ); 
[ALLEEG EEG] = eeg_store(ALLEEG, EEG, CURRENTSET);

%% // Bin Based Epochs
EEG = pop_epochbin( EEG , [0.0  1000.0],  [ 0 100]); 
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 4,'gui','off'); 

%% // Removing Eye Blinks
EEG  = pop_artblink( EEG , 'Blinkwidth',  400, 'Channel',  14, 'Crosscov',  0.7, ...
    'Flag',  1, 'Twindow', [ 0 992.2] ); 
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 5,'gui','off'); 

%% // Removing step like artifacts

EEG  = pop_artstep( EEG , 'Channel',  1:14, 'Flag',  1, 'Threshold',  100, 'Twindow', [ 0 992.2],...
    'Windowsize',  200, 'Windowstep',  50 ); 
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 6,'gui','off'); 
EEG = eeg_checkset( EEG );
pop_eegplot( EEG, 1, 1, 1);

% Now compute avg erps' and export them in .txt(universal) format using ERPLAB GUI

%% // Exporting individual ERP data
EEG = eeg_checkset( EEG );
pop_export(EEG,'C:\\Users\\harsh\\Downloads\\eeglab13_4_4b\\something','precision',4); % change file name and directory

% USE THE FILE GENERATED BY THE EXPORT IN FEATURE EXTRACTION CODE