%%________________________Creating Event List ___________________________%%


%% // Importing Eye Tracking Data
fid = fopen('C:\Users\harsh\Downloads\eeglab13_4_4b\ferda1eye.csv') ; % File generated by Eye Tribe
A = textscan( fid , '%s %f %u %s ' , 'Delimiter',',' , 'HeaderLines',0) ;
fclose(fid) ;

%% // Importing EEG Data
eegData = csvread('C:\Users\harsh\Downloads\eeglab13_4_4b\Ferda1.csv'); % Data from EPOC Headset

%% // Time sync
eyeT = A(:,2); % Filters EYETracking Time Stamps
eyeT = cell2mat(eyeT); % Converts cell array to numeric

eegT = eegData(1,18); % filters EEG Time Stamps
eegT = eegT*1000; % Converts into milliseconds

latency = (eyeT - eegT)/1000; % Latency in seconds( 1 second= 1000 ms)

%% // Getting Words' Classes
Class = A(:,4); % Filters Word's Classes

%% // Printing EventFile
fid = fopen('C:\Users\harsh\Downloads\eeglab13_4_4b\Final\im.txt','wt'); %% Opens file
fprintf(fid,'latency type\n')
for i = 1:numel(latency)
    fprintf(fid,'%f %s \n', latency(i), Class{1}{i}); %% Writes to the file
end
fclose(fid);

